version: '3'
services:
    backend:
        build: ./backend
        ports:
            - '5000:5000'
        volumes:
            - ./backend/src:/usr/src/app/src

    postgres:
        image: postgres:11-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
